[app]
environment="development"
port="1998"
jwtkey=""

[database]
host=""
port="5432"
dbname="mapmarker"
username=""
password=""

[ldap]
enable=true
basedn=""
binddn=""
port="389"
host="localhost"
bindpassword=""
filter="(uid=%s)"
defaultrole="user"