// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Marker struct {
	ID          int     `json:"id"`
	Label       string  `json:"label"`
	Latitude    string  `json:"latitude"`
	Longitude   string  `json:"longitude"`
	Address     string  `json:"address"`
	ImageLink   *string `json:"image_link"`
	Link        *string `json:"link"`
	Type        string  `json:"type"`
	Description *string `json:"description"`
	ToTime      *string `json:"to_time"`
	FromTime    *string `json:"from_time"`
	CreatedAt   string  `json:"created_at"`
	CreatedBy   *User   `json:"created_by"`
	UpdatedAt   string  `json:"updated_at"`
	UpdatedBy   *User   `json:"updated_by"`
}

type NewMarker struct {
	Label       string  `json:"label"`
	Latitude    string  `json:"latitude"`
	Longitude   string  `json:"longitude"`
	Address     string  `json:"address"`
	ImageLink   *string `json:"image_link"`
	Link        *string `json:"link"`
	Type        string  `json:"type"`
	Description *string `json:"description"`
	ToTime      *string `json:"to_time"`
	FromTime    *string `json:"from_time"`
	UserID      int     `json:"user_id"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type User struct {
	ID        int    `json:"id"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

type UserFilter struct {
	Username *string `json:"username"`
	Role     *string `json:"role"`
}
